# Generated by Django 6.0.6 on 2026-06-25 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(default='Без названия', max_length=100)),
                ('content', models.TextField()),
                ('language', models.CharField(choices=[('javascript', 'JavaScript'), ('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('html', 'HTML'), ('css', 'CSS'), ('php', 'PHP'), ('ruby', 'Ruby'), ('go', 'Go'), ('rust', 'Rust'), ('sql', 'SQL'), ('text', 'Текст')], default='javascript', max_length=20)),
                ('category', models.CharField(choices=[('work', 'Работа'), ('personal', 'Личная жизнь'), ('food', 'Еда'), ('study', 'Учеба'), ('travel', 'Путешествия'), ('health', 'Здоровье'), ('entertainment', 'Развлечения'), ('other', 'Другое')], default='other', max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('username', models.CharField(default='Гость', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
