# Generated by Django 6.0.6 on 2026-06-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastes',
            options={'verbose_name': 'заметка', 'verbose_name_plural': 'заметки'},
        ),
    ]
